# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8f51f5c676995059b125a8135936ca3fa1fc3a6bcd48f95a51c202811c8511fa1da397b8de73dd977fa6e0b846805467a064ee1f32b3a95b0d3f4adbc2bd34

test:
  secret_key_base: c394b2b95fb0e7e1003aa575f69b721771b50c73064c918c7c38e5f3ae99377a7ba685bce91b73e26882a1f61e1e84cccf894e1df945034dfb0832b4c18cf255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
